# Generated by Django 6.0.5 on 2026-06-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crop_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='crop_y',
            field=models.IntegerField(default=0),
        ),
    ]
