# Generated by Django 6.0.5 on 2026-06-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_crop_x_post_crop_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='crop_x',
        ),
        migrations.RemoveField(
            model_name='post',
            name='crop_y',
        ),
    ]
